types = [
    {
        "name": "ILE",
        "scores": {
            "e": 85,
            "n": 100,
            "t": 70,
            "p": 100,
            "peri": 70,
            "asc": 100,
            "que": 85,
            "right": 70,
            "stat": 85,
            "pos": 70,
            "con": 70,
            "demo": 100,
            "inci": 70,
            "tact": 70,
            "yield": 70,
        }
    },
    {
        "name": "SEI",
        "scores": {
            "e": 15,
            "n": 30,
            "t": 0,
            "p": 85,
            "peri": 100,
            "asc": 70,
            "que": 15,
            "right": 70,
            "stat": 15,
            "pos": 40,
            "con": 15,
            "demo": 85,
            "inci": 85,
            "tact": 15,
            "yield": 85,
        }
    },
    {
        "name": "ESE",
        "scores": {
            "e": 85,
            "n": 15,
            "t": 0,
            "p": 15,
            "peri": 85,
            "asc": 70,
            "que": 0,
            "right": 30,
            "stat": 30,
            "pos": 100,
            "con": 70,
            "demo": 70,
            "inci": 30,
            "tact": 85,
            "yield": 40,
        }
    },
    {
        "name": "LII",
        "scores": {
            "e": 0,
            "n": 85,
            "t": 100,
            "p": 15,
            "peri": 85,
            "asc": 85,
            "que": 100,
            "right": 30,
            "stat": 85,
            "pos": 30,
            "con": 40,
            "demo": 100,
            "inci": 30,
            "tact": 15,
            "yield": 30,
        }
    },
    {
        "name": "EIE",
        "scores": {
            "e": 85,
            "n": 85,
            "t": 15,
            "p": 30,
            "peri": 15,
            "asc": 100,
            "que": 100,
            "right": 85,
            "stat": 30,
            "pos": 15,
            "con": 100,
            "demo": 0,
            "inci": 70,
            "tact": 30,
            "yield": 15,
        }
    },
    {
        "name": "LSI",
        "scores": {
            "e": 15,
            "n": 0,
            "t": 100,
            "p": 0,
            "peri": 15,
            "asc": 70,
            "que": 15,
            "right": 70,
            "stat": 85,
            "pos": 70,
            "con": 30,
            "demo": 0,
            "inci": 60,
            "tact": 70,
            "yield": 15,
        }
    },
    {
        "name": "SLE",
        "scores": {
            "e": 100,
            "n": 0,
            "t": 100,
            "p": 70,
            "peri": 0,
            "asc": 85,
            "que": 15,
            "right": 30,
            "stat": 100,
            "pos": 30,
            "con": 85,
            "demo": 15,
            "inci": 15,
            "tact": 15,
            "yield": 60,
        }
    },
    {
        "name": "IEI",
        "scores": {
            "e": 15,
            "n": 100,
            "t": 0,
            "p": 100,
            "peri": 40,
            "asc": 85,
            "que": 70,
            "right": 30,
            "stat": 0,
            "pos": 70,
            "con": 30,
            "demo": 30,
            "inci": 30,
            "tact": 85,
            "yield": 70,
        }
    },
    {
        "name": "SEE",
        "scores": {
            "e": 100,
            "n": 15,
            "t": 30,
            "p": 100,
            "peri": 0,
            "asc": 30,
            "que": 70,
            "right": 85,
            "stat": 85,
            "pos": 85,
            "con": 15,
            "demo": 70,
            "inci": 30,
            "tact": 15,
            "yield": 15,
        }
    },
    {
        "name": "ILI",
        "scores": {
            "e": 0,
            "n": 85,
            "t": 100,
            "p": 85,
            "peri": 15,
            "asc": 30,
            "que": 40,
            "right": 70,
            "stat": 15,
            "pos": 0,
            "con": 100,
            "demo": 85,
            "inci": 15,
            "tact": 85,
            "yield": 15,
        }
    },
    {
        "name": "LIE",
        "scores": {
            "e": 100,
            "n": 70,
            "t": 100,
            "p": 30,
            "peri": 15,
            "asc": 15,
            "que": 0,
            "right": 30,
            "stat": 30,
            "pos": 85,
            "con": 0,
            "demo": 85,
            "inci": 70,
            "tact": 15,
            "yield": 70,
        }
    },
    {
        "name": "ESI",
        "scores": {
            "e": 0,
            "n": 0,
            "t": 30,
            "p": 0,
            "peri": 30,
            "asc": 15,
            "que": 85,
            "right": 15,
            "stat": 85,
            "pos": 15,
            "con": 85,
            "demo": 60,
            "inci": 70,
            "tact": 70,
            "yield": 85,
        }
    },
    {
        "name": "LSE",
        "scores": {
            "e": 70,
            "n": 0,
            "t": 100,
            "p": 0,
            "peri": 70,
            "asc": 0,
            "que": 70,
            "right": 70,
            "stat": 40,
            "pos": 30,
            "con": 30,
            "demo": 15,
            "inci": 15,
            "tact": 70,
            "yield": 85,
        }
    },
    {
        "name": "EII",
        "scores": {
            "e": 0,
            "n": 85,
            "t": 15,
            "p": 15,
            "peri": 100,
            "asc": 30,
            "que": 30,
            "right": 70,
            "stat": 70,
            "pos": 70,
            "con": 85,
            "demo": 30,
            "inci": 30,
            "tact": 40,
            "yield": 85,
        }
    },
    {
        "name": "IEE",
        "scores": {
            "e": 85,
            "n": 100,
            "t": 0,
            "p": 100,
            "peri": 85,
            "asc": 40,
            "que": 30,
            "right": 15,
            "stat": 70,
            "pos": 40,
            "con": 0,
            "demo": 30,
            "inci": 85,
            "tact": 85,
            "yield": 30,
        }
    },
    {
        "name": "SLI",
        "scores": {
            "e": 0,
            "n": 15,
            "t": 70,
            "p": 70,
            "peri": 100,
            "asc": 0,
            "que": 85,
            "right": 15,
            "stat": 15,
            "pos": 70,
            "con": 70,
            "demo": 30,
            "inci": 70,
            "tact": 30,
            "yield": 15,
        }
    },

];
